### ISSUE TITLE
/user/Hans8 matches /user/{username:[a-z]+}

### ISSUE THREAD

**Issue by dominikzogg** [azjezz/hack-routing#1]
**Describe the bug**
/user/Hans8 matches /user/{username:[a-z]+}, which shouldn't be the case

**To Reproduce**
Code to reproduce the behavior:
https://github.com/azjezz/hack-routing/blob/main/examples/simple.php#L42

**Expected behavior**
i would expect a 404 route not found

**Environment (please complete the following information):**
 - OS: Ubuntu
 - PHP version 8.0.7
 - Version main branch

**Additional context**

**Comment by azjezz** [comment]
i just tested this locally, and it seems to work as expected ( returns 404 ), do you have another script to reproduce this?

https://github.com/azjezz/hack-routing/commit/1df145e0103a3efdb644cf7086e3b679b6015b52

**Comment by dominikzogg** [comment]
```php
<?php

declare(strict_types=1);

namespace App;

use Chubbyphp\Framework\Application;
use Chubbyphp\Framework\Middleware\ExceptionMiddleware;
use Chubbyphp\Framework\Middleware\RouteMatcherMiddleware;
use Chubbyphp\Framework\RequestHandler\CallbackRequestHandler;
use Chubbyphp\Framework\Router\HackRouting\RouteMatcher;
use Chubbyphp\Framework\Router\Route;
use Chubbyphp\Framework\Router\Routes;
use Psr\Http\Message\ServerRequestInterface;
use Slim\Psr7\Factory\ResponseFactory;
use Slim\Psr7\Factory\ServerRequestFactory;

$loader = require __DIR__.'/vendor/autoload.php';

$responseFactory = new ResponseFactory();

$app = new Application([
    new ExceptionMiddleware($responseFactory, true),
    new RouteMatcherMiddleware(new RouteMatcher(new Routes([
        Route::get('/hello/{name:[a-z]+}', 'hello', new CallbackRequestHandler(
            function (ServerRequestInterface $request) use ($responseFactory) {
                $name = $request->getAttribute('name');
                $response = $responseFactory->createResponse();
                $response->getBody()->write(sprintf('Hello, %s', $name));

                return $response;
            }
        ))
    ])), $responseFactory),
]);

$app->emit($app->handle((new ServerRequestFactory())->createFromGlobals()));
```
https://github.com/chubbyphp/chubbyphp-framework-router-hack-routing/blob/master/src/RouteMatcher.php

**Comment by azjezz** [comment]
hm, noticed you are using file cache always, did you delete the cache after adding `:[a-z]+`? :)
```sh
rm /tmp/hack-routing/* -rf
```

i suggest adding a new argument somewhere to control cache, and whether to use file cache or apcu ( which can be more performant under certain conditions )

**Comment by dominikzogg** [comment]
@azjezz i am not sure, will check! refactoring to beeing able inject the cache is on my own todo list anyway

**Comment by azjezz** [comment]
i cloned your project locally and the example seems to work as i predicated, this is probably a caching issue.

**Comment by dominikzogg** [comment]
checked it, your right!

**Comment by dominikzogg** [comment]
thanks for testing
